server:
  port: 9000
spring:
  application:
    name: example
  datasource:
    url: jdbc:mysql://localhost:3306/padre
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


